services:
  - type: web
    name: kick-24-7-stream
    runtime: docker
    plan: starter
    healthCheckPath: /health

    envVars:
      - key: ADMIN_PASSWORD
        sync: false

      - key: FLASK_SECRET
        generateValue: true

      - key: KICK_RTMP_URL
        sync: false

      - key: KICK_STREAM_KEY
        sync: false

      - key: VIDEO_FILE
        value: video.mp4
